# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 00:31
from __future__ import unicode_literals

from django.db import migrations, models
import draceditor.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', draceditor.models.DraceditorField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
