# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 00:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20170126_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='description',
            new_name='shortDes',
        ),
    ]
