# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 00:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170126_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='shortDes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
